MyMDB/urls.py
from django.contrib import admin
from django.urls import path, include
import core.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(core.urls, namespace='core'))
]

core/urls.py
from django.urls import path
from . import views

app_name = 'core'
urlpatterns = [
    path('movies',
         views.MovieList.as_view(),
         name='MovieList'),

    path('movie/<int:pk>',
         views.MovieDetail.as_view(),
         name='MovieDetail'),

    path('person/<int:pk>',
         views.PersonDetail.as_view(),
         name='PersonDetail'),
]

core/models.py
from django.db import models


class MovieManager(models.Manager):

    def all_with_related_persons(self):
        qs = self.get_queryset()
        qs = qs.select_related('director')
        qs = qs.prefetch_related('writers', 'actors')
        return qs


class Movie(models.Model):
    director = models.ForeignKey(to="Person", on_delete=models.SET_NULL, related_name='directed', null=True, blank=True)
    writers = models.ManyToManyField(to="Person", related_name='writing_credits', blank=True)
    actors = models.ManyToManyField(to="Person", through="Role", related_name='acting_credits', blank=True)
    NOT_RATED = 0
    RATED_G = 1
    RATED_PG = 2
    RATED_R = 3
    RATINGS = (
        (NOT_RATED, 'NR - Not Rated'),
        (RATED_G, 'G - General Audiences'),
        (RATED_PG, 'PG - Parental Guidance' 'Suggested'),
        (RATED_R, 'R - Restricted'),
    )
    title = models.CharField(max_length=140)
    plot = models.TextField()
    year = models.PositiveIntegerField()
    rating = models.IntegerField(
        choices=RATINGS,
        default=NOT_RATED)
    runtime = models.PositiveIntegerField()
    website = models.URLField(blank=True)

    class Meta:
        ordering = ('-year', 'title')

    def __str__(self):
        return '{} ({})'.format(self.title, self.year)


class PersonManager(models.Manager):
    def all_with_prefetch_movies(self):
        qs = self.get_queryset()
        return qs.prefetch_related(
            'directed',
            'writing_credits',
            'role_set__movie')


class Person(models.Model):
    first_name = models.CharField(max_length=140)
    last_name = models.CharField(max_length=140)
    born = models.DateField()
    died = models.DateField(null=True, blank=True)

    objects = PersonManager()

    class Meta:
        ordering = ('last_name', 'first_name')

    def __str__(self):
        if self.died:
            return '{}, {} ({} - {})'.format(
                self.last_name,
                self.first_name,
                self.born,
                self.died)
        return '{}, {} ({})'.format(
            self.last_name,
            self.first_name,
            self.born)


class Role(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.DO_NOTHING)
    person = models.ForeignKey(Person, on_delete=models.DO_NOTHING)
    name = models.CharField(max_length=140)

    def __str__(self):
        return "{} {} {}".format(self.movie_id, self.person_id, self.name)

    class Meta:
        unique_together = ('movie', 'person', 'name')

core/views.py
from django.shortcuts import render
from .models import Movie, Person
from django.views.generic import ListView, DetailView


class MovieList(ListView):
    model = Movie
    paginate_by = 10


class MovieDetail(DetailView):
    model = Movie


class PersonDetail(DetailView):
    queryset = Person.objects.all_with_prefetch_movies()


#for z in range(150):
    #Movie.objects.create(
        #title='Title {}'.format(z),
        #year=1990 + z,
        #runtime=100,)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>{% block title %}MyMDB{% endblock %}</title>
    <style>
        .myndb-masthead {
            background-color: #EEEEEE;
            margin-bottom: 1em;
        }
    </style>
</head>

<body>
    <div class="myndb-masthead">
        <div class="container">
            <nav class="nav">
                <div class="navbar-brand">MyMDB</div>
                <a class="nav-link" href="{% url 'core:MovieList' %}">Movies</a>
            </nav>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-sm-8 mymdb-main">
                    {% block main %}{% endblock %}
                </div>
                <div class="col-sm-3 offset-sm-1 myndb-sidebar">
                    {% block sidebar %}{% endblock %}
                </div>
            </div>
        </div>
    </div>
</body>
</html>

templates/core/movie_detail.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
        {{ object.title }} - {{ block.super }}
    {% endblock %}
</head>
<body>
    {% block main %}
        <h1>{{ object }}</h1>
        <p class="lead">
            {{ object.plot }}
        </p>
    {% endblock %}

    {% block sidebar %}
        <div>
            This movie is rated:
                <span class="badge badge-primary">
                    {{ object.get_rating_display }}
                </span>
        </div>
    {% endblock %}
</body>
</html>

templates/core/movie_list.html
<!DOCTYPE html>
{% extends 'base.html' %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}All The Movies{% endblock %}
</head>
<body>
    {% block main %}
        <ul>
            {% for movie in object_list %}
                <li>
                    <a href="{% url 'core:MovieDetail' pk=movie.id %}">
                        {{ movie }}
                    </a>
                </li>
            {% endfor %}
        </ul>
        {% if is_paginated %}
            <nav>
            <ul class="pagination">
            <li class="page-item">
                <a href="{% url 'core:MovieList' %}?page=1" class="page-link">
                    First
                </a>
            </li>
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a href="{% url 'core:MovieList' %}?page={{ page_obj.previous_page_number }}" class="page-link">
                        {{ page_obj.previous_page_number }}
                    </a>
                </li>
            {% endif %}
            <li class="page-item active">
                <a href="{% url 'core:MovieList' %}?page={{ page_obj.number }}" class="page-link">
                    {{ page_obj.number }}
                </a>
            </li>
            {% if page_obj.has_next %}
            <li class="page-item">
                <a href="{% url 'core:MovieList' %}?page={{ page_obj.next_page_number }}" class="page-link">
                    {{ page_obj.next_page_number }}
                </a>
            </li>
            {% endif %}
            <li class="page-item">
                <a href="{% url 'core:MovieList' %}?page=last" class="page-link">
                Last
                </a>
            </li>
            </ul>
            </nav>
        {% endif %}
    {% endblock %}
</body>
</html>

templates/core/person_detail.html
<!DOCTYPE html>
{% extends 'base.html' %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
    {{ object.first_name }}
    {{ object.last_name }}
    {% endblock %}
</head>
<body>
    {% block main %}
        <h1>{{ object }}</h1>
        <h2>Actor</h2>
        <ul>
            {% for role in object.role_set.all %}
                <li>
                    <a href="{% url 'core:MovieDetail' role.movie.id %}">
                        {{ role.name }}
                    </a>:
                    {{ role.name }}
                </li>
            {% endfor %}
        </ul>
        <h2>Writer</h2>
        <ul>
            {% for movie in object.writing_credits.all %}
                <li>
                    <a href="{% url 'core:MovieDetail' movie.id %}">
                        {{ movie }}
                    </a>
                </li>
            {% endfor %}
        </ul>
        <h2>Director</h2>
        <ul>
            {% for movie in object.directed.all %}
                <li>
                    <a href="{% url 'core:MovieDetail' movie.id %}">
                        {{ movie }}
                    </a>
                </li>
            {% endfor %}
        </ul>
    {% endblock %}
</body>
</html>